### ISSUE TITLE
Disabled Next button still works

### ISSUE THREAD

**Issue by NickBarrett** [cornflourblue/angular2-pagination-example#1]
Hi there,

Thanks for the example code =)

I found that clicking the "Next" button when you're already on the last page still increases pager.currentPage. I'm still pretty new to js and ts so I can't offer any solutions at the moment, but thought you would want to know. I'f I work it out I'll let you know ;)

Thanks again

**Comment by NickBarrett** [comment]
I've got it now.

So using `[ngClass]="{disabled:pager.currentPage === pager.totalPages}"` just sets the `li` class but doesn't actually "disable" anything. The reason it was working for the Previous button was the code `if (page < 1) { return; }` in the `setPage(page: number)` function. Adding `if (page > this.pager.totalPages) { return; }` to the start of that function solves the problem.

Thanks again =)

**Comment by cornflourblue** [comment]
Thanks Nick, I've just updated the code to fix the issue.

Cheers,
Jason
