### ISSUE TITLE
Angular 4

### ISSUE THREAD

**Issue by vdykcj** [cornflourblue/angular2-pagination-example#6]
Hi,
Is Angular 4 supported. Trying to run the sample downloaded from GitHub but simply getting below response:
npm ERR! angular2-pagination-example@1.0.0 start: `tsc && concurrently "npm run tsc:w" "npm run lite" `
npm ERR! Exit status 2

More detailed info in attached file.

As I am new to Angular, how can I get it working in angular 4 project (Running Win 10, Angular 4)?

[npm-debug.zip](https://github.com/cornflourblue/angular2-pagination-example/files/1169068/npm-debug.zip)

**Comment by cornflourblue** [comment]
Yes it's updated to Angular 5
